from typing import Any, Protocol, TypeVar

T = TypeVar("T")


class StateStorage(Protocol):
    async def get(self, key: str, type_hint: Any = None) -> Any: ...
    async def set(self, key: str, value: Any, ttl: int | None = None) -> None: ...
    async def delete(self, key: str) -> None: ...
    async def clear(self) -> None: ...
