"""Public media-provider contracts."""

from .delivery import DeliveryAsset, TelegramDelivery
from .models import (
    ClipInterval,
    DeliveredItem,
    DeliveryReceipt,
    DeliveryStatus,
    DeliveryTarget,
    MediaCandidate,
    MediaItem,
    MediaKind,
    MediaRequest,
    QualityPolicy,
    ResolvedMedia,
    UnsupportedMediaUrlError,
    canonicalize_media_url,
    request_cache_key,
)
from .pipeline import (
    ArtifactValidationError,
    CallbackDataError,
    MediaDeliveryUncertainError,
    MediaPipeline,
    MediaPipelineError,
    MediaResolutionError,
    build_default_pipeline,
    build_media_request,
    decode_callback_data,
    decode_callback_payload,
    encode_callback_data,
    request_from_download_context,
)
from .transport import (
    DECIMAL_MEDIA_LIMIT,
    MaterializedItem,
    MediaSizeExceeded,
    MediaTransport,
    UnsafeMediaURL,
    URLPolicy,
)
from .validation import (
    CandidateRejectionReason,
    CandidateValidationResult,
    validate_candidate,
)

__all__ = [
    "DECIMAL_MEDIA_LIMIT",
    "ArtifactValidationError",
    "CallbackDataError",
    "CandidateRejectionReason",
    "CandidateValidationResult",
    "ClipInterval",
    "DeliveredItem",
    "DeliveryAsset",
    "DeliveryReceipt",
    "DeliveryStatus",
    "DeliveryTarget",
    "MaterializedItem",
    "MediaCandidate",
    "MediaDeliveryUncertainError",
    "MediaItem",
    "MediaKind",
    "MediaPipeline",
    "MediaPipelineError",
    "MediaRequest",
    "MediaResolutionError",
    "MediaSizeExceeded",
    "MediaTransport",
    "QualityPolicy",
    "ResolvedMedia",
    "TelegramDelivery",
    "URLPolicy",
    "UnsafeMediaURL",
    "UnsupportedMediaUrlError",
    "build_default_pipeline",
    "build_media_request",
    "canonicalize_media_url",
    "decode_callback_data",
    "decode_callback_payload",
    "encode_callback_data",
    "request_cache_key",
    "request_from_download_context",
    "validate_candidate",
]
